apiVersion: v1
kind: Service
metadata:
  name: router-api
  namespace: skill-hub
  labels:
    app: router-api
    service: skill-hub
spec:
  selector:
    app: router-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: admin-api
  namespace: skill-hub
  labels:
    app: admin-api
    service: skill-hub
spec:
  selector:
    app: admin-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
